import { NextResponse } from 'next/server';
import { prisma } from '@/infrastructure/clients/prisma';
import * as cheerio from 'cheerio';
import { injectCtaBlocks } from '../pipeline/html-phase';
import { CtaTemplateData } from '../seo-cta-builder';
import { buildThemeStyles } from '@/shared/lib/build-theme-styles';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { itemIds, projectId, themeId } = body;

    if (!Array.isArray(itemIds) || itemIds.length === 0 || !projectId || !themeId) {
      return NextResponse.json({ success: false, error: '필수 파라미터가 누락되었습니다.' }, { status: 400 });
    }

    // 1. Fetch the Theme
    const theme = await prisma.articleTheme.findUnique({ where: { id: themeId } });
    if (!theme) {
      return NextResponse.json({ success: false, error: '선택한 테마를 찾을 수 없습니다.' }, { status: 404 });
    }

    let themeConfig: Record<string, any> = {};
    try {
      themeConfig = JSON.parse(theme.config);
    } catch (e) {
      return NextResponse.json({ success: false, error: '테마 설정 파싱 실패' }, { status: 500 });
    }

    // 2. Fetch the Articles
    const researches = await prisma.research.findMany({
      where: {
        projectId,
        itemId: { in: itemIds },
      },
    });

    if (researches.length === 0) {
      return NextResponse.json({ success: false, error: '선택한 글을 찾을 수 없습니다.' }, { status: 404 });
    }

    let successCount = 0;
    const errors: any[] = [];

    // 3. Process each Article
    for (const record of researches) {
      try {
        const pack = JSON.parse(record.pack);
        
        // Skip if not HTML type or missing content
        if (pack.contentType !== 'html' || !pack.content) continue;

        // --- Cheerio Parsing ---
        const $ = cheerio.load(pack.content, null, false); // false prevents adding <html><head><body> tags automatically
        
        // Remove ALL CTA related elements and old CP9 product cards/images if we want a full clean refresh
        // For safety, we remove EXACTLY elements that are generated by CTAs
        // .cp9-cta : All CTAs (Legacy and New)
        // .cp9-cta-block : New CTA system base
        // .cp9-curation-section, .cp9-product-image, .cp9-image-suggestion : Legacy or other auto-injected blocks if needed?
        // Let's only remove CTA blocks so we don't accidentally remove actual content
        $('*[class*="cp9-cta"]').remove();

        // Also remove old Style tags if they belong to CP9 themes
        $('style').each((_, el) => {
          const styleText = $(el).text();
          if (styleText.includes('/* CP9 아티클 테마 CSS */')) {
            $(el).remove();
          }
        });

        const cleanHtml = $.html();

        // --- Re-build CtaTemplateData ---
        const buildData: CtaTemplateData = {
          productName: pack.title,
          productImage: pack.productImage || pack.thumbnailUrl || '',
          buyUrl: pack.productUrl || `https://www.coupang.com/vp/products/${pack.itemId}`,
          persona: pack.persona || 'MASTER_CURATOR_H',
          productPrice: pack.priceKRW || undefined,
          isRocket: pack.isRocket || false,
          itemId: pack.itemId,
          projectId: record.projectId,
          articleType: (pack.articleType as any) || 'single',
        };

        // --- Inject New Theme ---
        let finalHtml = cleanHtml;
        const ctaBlocks = themeConfig?.ctaBlocks || [];
        
        if (ctaBlocks.length > 0) {
          const injectionResult = injectCtaBlocks(finalHtml, ctaBlocks, buildData);
          finalHtml = injectionResult.html + injectionResult.footerAppended;
        } else {
          // If the new theme uses Legacy CTA system (fallback)
          // We can't perfectly fallback to legacy since we bypassed runHtmlPhase, 
          // but the new system is the default now anyway.
        }

        // --- Prepend new Theme CSS ---
        const themeStyleTag = buildThemeStyles(themeConfig);
        finalHtml = themeStyleTag + finalHtml;

        // --- Strip any existing 쿠팡 파트너스 disclaimers (AI generated or old system generated) ---
        const rawDisclaimerRegex = /<p[^>]*>\s*※?\s*(?:이\s*포스팅은\s*)?쿠팡\s*파트너스\s*활동의\s*일환으로,?\s*이에\s*따른\s*일정액의\s*수수료를\s*제공받(?:습니다|을\s*수\s*있습니다)\.?\s*<\/p>/gi;
        finalHtml = finalHtml.replace(rawDisclaimerRegex, '');
        const textDisclaimerRegex = /※?\s*(?:이\s*포스팅은\s*)?쿠팡\s*파트너스\s*활동의\s*일환으로,?\s*이에\s*따른\s*일정액의\s*수수료를\s*제공받(?:습니다|을\s*수\s*있습니다)\.?/gi;
        finalHtml = finalHtml.replace(textDisclaimerRegex, '');

        // --- Append exact single standard disclaimer at the very bottom ---
        const disclaimerHtml = `<p style="font-size:11px;color:#999;text-align:center;margin:32px 0 8px;">※ 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받을 수 있습니다.</p>`;
        finalHtml = finalHtml + disclaimerHtml;

        // --- Save Back to DB ---
        pack.content = finalHtml;
        pack.updatedAt = new Date().toISOString();
        pack.appliedThemeId = themeId;

        await prisma.research.update({
          where: { projectId_itemId: { projectId: record.projectId, itemId: record.itemId } },
          data: { pack: JSON.stringify(pack) },
        });

        successCount++;
      } catch (err) {
        errors.push({ itemId: record.itemId, error: err instanceof Error ? err.message : String(err) });
      }
    }

    return NextResponse.json({ 
      success: true, 
      count: successCount, 
      total: itemIds.length,
      errors: errors.length > 0 ? errors : undefined
    });

  } catch (err) {
    console.error('[POST /api/item-research/sync-theme] Error:', err);
    return NextResponse.json({ success: false, error: '서버 내부 오류가 발생했습니다.' }, { status: 500 });
  }
}
